In [5]:
# Useful starting lines
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from helpers import *
%load_ext autoreload
%autoreload 2
# Additionally added libraries

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
#Load Data + take off the features of indexes in K vector
#here, take of only the record file name colomn = 1
K=[1]
[features_coarse,labels_coarse] = load_csv_data('../data/train_data/features_coarse_segmentation.csv', '../data/train_data/labels_coarse_segmentation.csv', K)
[features_fine,labels_fine] = load_csv_data('../data/train_data/features_fine_segmentation.csv', '../data/train_data/labels_fine_segmentation.csv', K)
[features_no,labels_no] = load_csv_data('../data/train_data/features_no_segmentation.csv', '../data/train_data/labels_no_segmentation.csv', K)

In [8]:
df, feat_details_coarse = analyse(features_coarse)
df

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
Statistics,,,,,,,,,,,,,,,,,,,,,
Mean,1719.500000,6.620349,6.632267,6.685465,6.726453,6.750291,6.777035,6.810756,6.840116,6.884302,...,0.074521,5.887959e-02,5.922868e-02,2.107058e-02,2.892611e-02,2.041860,34.382933,0.393169,0.300581,0.246802
Variance,986133.250000,9.225051,9.313901,9.458626,9.429533,9.434448,9.606391,9.729594,9.790135,9.888358,...,0.005938,4.365646e-03,4.883817e-03,9.155301e-04,1.546818e-03,0.634294,142.757857,0.202468,0.176221,0.151879
Std,993.042421,3.037277,3.051868,3.075488,3.070754,3.071555,3.099418,3.119230,3.128919,3.144576,...,0.077056,6.607304e-02,6.988431e-02,3.025773e-02,3.932961e-02,0.796426,11.948132,0.449964,0.419786,0.389717
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,9.155689e-08,2.021244e-07,3.515938e-07,4.901346e-07,1.000000,1.000000,0.000000,0.000000,0.000000
max,3439.000000,29.000000,30.000000,31.000000,29.000000,29.000000,28.000000,29.000000,29.000000,29.000000,...,0.759942,6.645379e-01,7.044270e-01,3.362513e-01,4.031848e-01,3.000000,97.000000,1.000000,1.000000,1.000000
n-NaNs,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
median,1719.500000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,7.000000,...,0.050080,3.725905e-02,3.463339e-02,1.083558e-02,1.559970e-02,2.000000,34.382933,0.000000,0.000000,0.000000

In [9]:
[df, feat_details_fine] = analyse(features_fine)
df

,0,1,2,3,4,5,6,7,8,9,...,62,63,64,65,66,67,68,69,70,71
Statistics,,,,,,,,,,,,,,,,,,,,,
Mean,3.504000e+03,4.351833,4.360964,4.412470,4.473962,4.503781,4.521758,4.554002,4.593523,4.609645,...,9.386090e-02,0.060585,0.048999,2.073963e-02,2.870803e-02,2.051505,34.430037,0.389357,0.293480,0.248966
Variance,4.093840e+06,1.635095,1.609468,1.629127,1.636396,1.698409,1.659428,1.760281,1.804387,1.800540,...,9.876647e-03,0.005661,0.004267,1.019225e-03,1.828860e-03,0.635241,139.161377,0.204158,0.175747,0.155380
Std,2.023324e+03,1.278708,1.268648,1.276373,1.279217,1.303230,1.288188,1.326756,1.343275,1.341842,...,9.938132e-02,0.075242,0.065325,3.192530e-02,4.276518e-02,0.797020,11.796668,0.451839,0.419222,0.394182
min,0.000000e+00,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,...,7.349431e-07,0.000001,0.000006,7.740565e-08,4.191298e-07,1.000000,1.000000,0.000000,0.000000,0.000000
max,7.008000e+03,17.000000,16.000000,16.000000,19.000000,20.000000,18.000000,18.000000,23.000000,21.000000,...,9.351590e-01,0.802540,0.961117,3.635824e-01,6.842158e-01,3.000000,89.000000,1.000000,1.000000,1.000000
n-NaNs,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
median,3.504000e+03,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,...,6.173333e-02,0.035651,0.026557,9.871327e-03,1.382644e-02,2.000000,34.430037,0.000000,0.000000,0.000000

In [12]:
[df, feat_details_no] = analyse(features_no)
df

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
Statistics,,,,,,,,,,,,,,,,,,,,,
Mean,829.000000,60.343580,60.408077,60.696203,60.792646,60.872212,60.962628,61.091621,61.164557,61.231465,...,0.094751,0.059965,0.060062,0.020844,0.029684,2.028330,34.321509,0.389693,0.296564,0.251356
Variance,229356.666667,285.705943,281.630339,284.520124,280.680332,279.441175,279.392214,283.053691,279.608243,282.234549,...,0.005658,0.003266,0.003498,0.000643,0.001327,0.626684,135.543723,0.198200,0.171242,0.150804
Std,478.911961,16.902838,16.781846,16.867724,16.753517,16.716494,16.715030,16.824200,16.721490,16.799838,...,0.075219,0.057151,0.059142,0.025349,0.036427,0.791634,11.642325,0.445197,0.413814,0.388335
min,0.000000,12.000000,12.000000,12.000000,13.000000,13.000000,13.000000,13.000000,14.000000,11.000000,...,0.000075,0.000121,0.000076,0.000014,0.000004,1.000000,1.000000,0.000000,0.000000,0.000000
max,1658.000000,106.000000,113.000000,111.000000,95.000000,94.000000,91.000000,103.000000,99.000000,108.000000,...,0.531806,0.438357,0.451244,0.292188,0.344574,3.000000,97.000000,1.000000,1.000000,1.000000
n-NaNs,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
median,829.000000,67.000000,67.000000,67.000000,68.000000,68.000000,68.000000,68.000000,68.000000,68.000000,...,0.074775,0.043003,0.041059,0.012606,0.017672,2.000000,34.321509,0.000000,0.000000,0.000000

In [13]:
#Standardize
feat_details_coarse=standardize(features_coarse, feat_details_coarse)
feat_details_fine=standardize(features_fine, feat_details_fine)
feat_details_no=standardize(features_no, feat_details_no)